/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:63bc19a9-50d2-4d87-bd83-54ff9ab32860",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_V2hyoUafy",
    "aws_user_pools_web_client_id": "3n9m0p5hrpvhvnc63d2rqued5f",
    "oauth": {}
};


export default awsmobile;
