/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

 

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a8fa7444-51ab-48eb-839c-402aa411fb6b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_L06F6CqGY",
    "aws_user_pools_web_client_id": "3a7l2fuvfo8idgkeg9h6ta4mte",
    "oauth": {}
};

 


export default awsmobile;